# PostgreSQL. Versions 8.2 and up are supported.
#
# Install the pg driver:
#   gem install pg
# On OS X with Homebrew:
#   gem install pg -- --with-pg-config=/usr/local/bin/pg_config
# On OS X with MacPorts:
#   gem install pg -- --with-pg-config=/opt/local/lib/postgresql84/bin/pg_config
# On Windows:
#   gem install pg
#       Choose the win32 build.
#       Install PostgreSQL and put its /bin directory on your path.
#
# Configure Using Gemfile
# gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: 5

development:
  <<: *default
  database: promo-rails_development
  username: postgres
  password:

staging:
  <<: *default
  user: promo
  password: <%= ENV['db_password'] %>
  host: localhost
  port: 5432
  database: promo-rails_staging

production:
  <<: *default
  user: promo
  password: <%= ENV['db_password'] %>
  host: localhost
  port: 5432
  database: promo-rails