# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 66c79e0b6a5c9b2f9b709942bb118bad195544f51ab712825a6e21d3a2c8bdad00a7eaf39c108000f024787f3050df01fd99ec45a0cb1341510874e0fc0bc984

test:
  secret_key_base: 5064b214bb8401e68335cb3a49473671297ed7bf1137137e15f9713876aa94cbf0fca908c11ba3eaea7250bae1eeb152e628f9b1a975615b4e4eef2d90905091

# Do not keep production secrets in the repository,
# instead read values from the environment.
staging:
  secret_key_base: <%= ENV["secret_key_base"] %>

production:
  secret_key_base: <%= ENV["secret_key_base"] %>
